workflows:
  android:
    name: Android Build (Debug)
    max_build_duration: 60
    environment:
      vars:
        FLAVOR: "debug"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Add Platform
        script: |
          npx cap add android
      - name: Build Android
        script: |
          ionic build
          npx cap build android
      - name: Archive artifacts
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

  ios:
    name: Ios Debug
    max_build_duration: 60
    environment:
      vars:
        FLAVOR: "debug"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli
      - name: Build iOS
        script: |
          ionic build
          npx cap add ios
          npx cap build ios
    artifacts:
      - ios/App/App.xcarchive/Products/Applications/App.ipa
