workflows:
  android-capacitor-workflow:
    name: Android Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Install npm dependencies for Ionic Capacitor project
        script: |
          npm install
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build App
        script: |
          ionic build
          ionic cap add android
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Build Android debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
